kind: pipeline
name: default

steps:
  - name: dco
    image: algernon/drone-plugin-dco
    depends_on: [ clone ]

  - name: lint-and-build
    image: rust:1
    commands:
      - rustup component add clippy rustfmt
      - cargo clippy
      - cargo fmt --check
      - cargo build -r
      - cargo test
