[package]
name = "kaleidoscope"
version = "0.1.0-snapshot"
description = "A library to talk with Kaleidoscope-powered devices using the Focus protocol"
categories = ["hardware-support"]
license = "GPL-3.0-only"
edition = "2021"
rust-version = "1.59.0"

[dependencies]
serialport = "4.2.0"
