name: Automatic builds

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install the rust toolchain
        run: |
          rustup toolchain install stable
          rustup default stable
          rustup component add clippy rustfmt

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Clippy
        run: cargo clippy

      - name: Format check
        run: cargo fmt --check

      - name: Documentation check
        run: cargo doc

      - name: Documentation compile check
        run: cargo test --doc

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Rust (Linux)
        if: runner.os == 'Linux'
        run: |
          rustup toolchain install stable
          rustup default stable

      - name: Install Rust (macOS/Windows)
        if: runner.os != 'Linux'
        run: |
          rustup toolchain install stable
          rustup default stable

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Test
        run: cargo test

      - name: Build
        run: cargo build --release

      - name: Prepare compressed binary (Linux)
        if: runner.os == 'Linux'
        run: |
          tar -cf - target/release/focus-send \
                    target/release/focus | \
              xz -c > target/release/kaleidoscope-focus.linux_amd64.tar.xz

      - name: Prepare compressed binary (macOS)
        if: runner.os == 'macOS'
        run: |
          tar -cf - target/release/focus-send \
                    target/release/focus | \
              xz -c > target/release/kaleidoscope-focus.macOS_amd64.tar.xz

      - name: Prepare compressed binary (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          tar -cf - target/release/focus-send \
                    target/release/focus | \
              xz -c > target/release/kaleidoscope-focus.windows_amd64.tar.xz

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-artifact
          path: |
            target/release/*.xz

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Discover the version tag
        run: echo "PKG_VERSION=$(cargo pkgid | cut -d@ -f2)" >>$GITHUB_ENV

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Delete the snapshot release
        if: ${{ contains(env.PKG_VERSION, 'snapshot') }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          TAG: v${{ env.PKG_VERSION }}
        shell: bash
        run: |
          gh release delete -y ${TAG} || true
          git tag -d ${TAG} || true
          git push origin :${TAG} || true

      - name: Recreate the snapshot release
        if: ${{ contains(env.PKG_VERSION, 'snapshot') }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          VERSION: ${{ env.PKG_VERSION }}
        shell: bash
        run: |
          gh release create -p -t "kaleidoscope-focus.rs ${VERSION}" \
                            -n "Development snapshot." \
                            v${VERSION}
          sleep 5s

      - name: Upload artifacts to the release
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          TAG: v${{ env.PKG_VERSION }}
        shell: bash
        run: |
          gh release upload ${TAG} artifacts/*/*.xz
