name: Automatic builds

on:
  push:
    branches:
      - main
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install the rust toolchain
        run: |
          rustup toolchain install stable
          rustup default stable
          rustup component add clippy rustfmt

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Clippy
        run: cargo clippy

      - name: Format check
        run: cargo fmt --check

      - name: Documentation check
        run: cargo doc

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Rust
        run: |
          rustup toolchain install stable
          rustup default stable

      - name: Install Additional targets (macOS)
        if: runner.os == 'macOS'
        run: |
          rustup target add aarch64-apple-darwin

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Test
        run: cargo test

      - name: Build (Linux, Windows)
        if: runner.os != 'macOS'
        run: cargo build --release

      - name: Build (macOS)
        if: runner.os == 'macOS'
        run: |
          cargo build --release
          cargo build --release --target aarch64-apple-darwin
          install -d target/universal-apple-darwin/release
          lipo target/release/focus \
               target/aarch64-apple-darwin/release/focus \
               -create -output target/universal-apple-darwin/release/focus
          lipo target/release/focus-send \
               target/aarch64-apple-darwin/release/focus-send \
               -create -output target/universal-apple-darwin/release/focus-send
          lipo -info target/universal-apple-darwin/release/focus \
                     target/universal-apple-darwin/release/focus-send

      - name: Prepare compressed binary (Linux)
        if: runner.os == 'Linux'
        run: |
          tar -cf - -C target/release focus-send focus | \
              xz -c > target/release/kaleidoscope-focus.linux_amd64.tar.xz

      - name: Prepare compressed binary (macOS)
        if: runner.os == 'macOS'
        run: |
          tar -cf - -C target/universal-apple-darwin/release focus-send focus | \
              xz -c > target/release/kaleidoscope-focus.macOS_universal.tar.xz

      - name: Prepare compressed binary (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          cd target/release && \
          7z a -tzip kaleidoscope-focus.windows_amd64.zip focus-send.exe focus.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-artifact
          path: |
            target/release/*.xz
            target/release/*.zip

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Snapshot release
        if: github.ref_type == 'branch'
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          UNRELEASED: "update"
          RELEASE_NAME_SUFFIX: " (snapshot build)"
        with:
          args: artifacts/*/*.xz artifacts/*/*.zip

      - name: Release
        if: github.ref_type == 'tag'
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          args: artifacts/*/*.xz artifacts/*/*.zip
